project:
  type: website

website:
  title: "SDS316: Data of the US Criminal Legal System"
  description: "Applicaiton Domain (context depth) class that focuses on understanding and working with data related to crime, policing, incarceration, detention, and other aspects of the Prison Industrial Complex (PIC) in the US"
  navbar:
    left:
      - href: index.qmd
        text: Homee
      - href: syllabus.qmd
        text: Syllabusw
      - href: schedule.qmd
        text: Scheduled
      - href: projects.qmd
        text: Projectsd
      - href: lectures.qmd
        text: Selected Lecturesd

format:
  html:
    theme: cosmo # Quarto comes with many built-in themes (bootswatch)
    toc: true

execute:
  freeze: auto